#
# Build stage
#

#FROM maven:3.6.0-jdk-11-slim AS build

#COPY ./user-management-service/src /home/app/src

#COPY ./user-management-service/pom.xml /home/app

#RUN mvn -f /home/app/pom.xml -Ptest clean package


#
# Package stage
#
FROM eclipse-temurin:17-jre-alpine AS deployment

LABEL maintainer="mashmoud.shehab@asset.com.eg"

COPY --from=build /home/app/target/user-management-service.jar /usr/local/lib/user-management-service.jar

ENTRYPOINT ["java","-jar","/usr/local/lib/user-management-service.jar"]