#
# Build stage
#

#FROM maven:3.6.0-jdk-11-slim AS build

#COPY ./dynamic-page-service/src /home/app/src

#COPY ./dynamic-page-service/pom.xml /home/app

#RUN mvn -f /home/app/pom.xml -Ptest clean package


#
# Package stage
#
FROM adoptopenjdk/openjdk11:jre-11.0.6_10-alpine AS deployment

LABEL maintainer="mashmoud.shehab@asset.com.eg"

COPY --from=build /home/app/target/dynamic-page-service.jar /usr/local/lib/dynamic-page-service.jar

ENTRYPOINT ["java","-jar","/usr/local/lib/dynamic-page-service.jar"]