DROP TABLE H_NOTEPAD_ENTRIES CASCADE CONSTRAINTS;

CREATE TABLE H_NOTEPAD_ENTRIES
(
  ENTRY_DATE     DATE                           DEFAULT sysdate               NOT NULL,
  MSISDN         VARCHAR2(13 BYTE)              NOT NULL,
  MSISDN_MOD_X   NUMBER(2)                      NOT NULL,
  USER_ID        NUMBER(6)                      NOT NULL,
  NOTEPAD_ENTRY  VARCHAR2(4000 BYTE)            NOT NULL,
  USER_NAME      VARCHAR2(200 BYTE)             NOT NULL
)
PARTITION BY RANGE (ENTRY_DATE)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY LIST (MSISDN_MOD_X)
SUBPARTITION TEMPLATE
  (SUBPARTITION SUBPARTITION_0 VALUES ('0'),
   SUBPARTITION SUBPARTITION_1 VALUES ('1'),
   SUBPARTITION SUBPARTITION_2 VALUES ('2'),
   SUBPARTITION SUBPARTITION_3 VALUES ('3'),
   SUBPARTITION SUBPARTITION_4 VALUES ('4'),
   SUBPARTITION SUBPARTITION_5 VALUES ('5'),
   SUBPARTITION SUBPARTITION_6 VALUES ('6'),
   SUBPARTITION SUBPARTITION_7 VALUES ('7'),
   SUBPARTITION SUBPARTITION_8 VALUES ('8'),
   SUBPARTITION SUBPARTITION_9 VALUES ('9')
  )           
(  
  PARTITION PARTITION_INITIAL VALUES LESS THAN (TO_DATE('2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))

  (SUBPARTITION SUBPARTITION_INITIAL_0 VALUES ('0'),
   SUBPARTITION SUBPARTITION_INITIAL_1 VALUES ('1'),
   SUBPARTITION SUBPARTITION_INITIAL_2 VALUES ('2'),
   SUBPARTITION SUBPARTITION_INITIAL_3 VALUES ('3'),
   SUBPARTITION SUBPARTITION_INITIAL_4 VALUES ('4'),
   SUBPARTITION SUBPARTITION_INITIAL_5 VALUES ('5'),
   SUBPARTITION SUBPARTITION_INITIAL_6 VALUES ('6'),
   SUBPARTITION SUBPARTITION_INITIAL_7 VALUES ('7'),
   SUBPARTITION SUBPARTITION_INITIAL_8 VALUES ('8'),
   SUBPARTITION SUBPARTITION_INITIAL_9 VALUES ('9')
 )
);
CREATE INDEX H_NOTEPAD_ENTRIES_MSISDN_NDC ON H_NOTEPAD_ENTRIES
(MSISDN);
