select 1 from dual;

--by Wael

  CREATE TABLE "CCAT_DEV2"."H_NOTEPAD_ENTRIES" 
   (	"ENTRY_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"MSISDN_MOD_X" NUMBER(2,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"NOTEPAD_ENTRY" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY LIST ("MSISDN_MOD_X") 
 (PARTITION "P0"  VALUES (0) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P1"  VALUES (1) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P2"  VALUES (2) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P3"  VALUES (3) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P4"  VALUES (4) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P5"  VALUES (5) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P6"  VALUES (6) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P7"  VALUES (7) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P8"  VALUES (8) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "P9"  VALUES (9) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) ;

  CREATE INDEX "CCAT_DEV2"."H_NOTEPAD_ENTRIES_MSISDN_NDC" ON "CCAT_DEV2"."H_NOTEPAD_ENTRIES" ("MSISDN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



--by Wael

  CREATE TABLE "CCAT_DEV2"."LK_REFILL_PAYMENT_PROFILE" 
   (	"REFILL_PROFILE_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"REFILL_PROFILE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AMOUNT_FROM" NUMBER(12,2) NOT NULL ENABLE, 
	"AMOUNT_TO" NUMBER(12,2) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_LK_REFILL_PAYMENT_PROFILE" ON "CCAT_DEV2"."LK_REFILL_PAYMENT_PROFILE" ("REFILL_PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  
  --by Wael
  
	
	 CREATE TABLE "CCAT_DEV2"."LK_ACCUMULATORS" 
	   (	"ACC_ID" NUMBER(2,0) NOT NULL ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_LK_ACCUMULATORS" ON "CCAT_DEV2"."LK_ACCUMULATORS" ("ACC_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;





	 CREATE TABLE "	CCAT_DEV2"."LK_DED_ACCOUNTS" 
	   (	"DA_ID" NUMBER(2,0) NOT NULL ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_LK_DED_ACCOUNTS" ON "CCAT_DEV2"."LK_DED_ACCOUNTS" ("DA_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;


  
	  CREATE TABLE "CCAT_DEV2"."ADM_BUSINESS_PLANS" 
	   (	"ID" NUMBER(6,0) NOT NULL ENABLE, 
		"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
		"CODE" NUMBER(4,0) NOT NULL ENABLE, 
		"SERVICE_CLASS_ID" NUMBER(6,0) NOT NULL ENABLE, 
		"HLR_ID" NUMBER(6,0) NOT NULL ENABLE, 
		"CAMEL_ID" NUMBER(6,0) NOT NULL ENABLE, 
		"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
		"ACTIVATION_PLAN" NUMBER DEFAULT 0, 
		 CONSTRAINT "ADM_BUSINESS_PLANS_R03" FOREIGN KEY ("SERVICE_CLASS_ID")
		  REFERENCES "CCAT_DEV2"."ADM_SERVICE_CLASSES" ("ID") DISABLE, 
		 CONSTRAINT "ADM_BUSINESS_PLANS_R04" FOREIGN KEY ("IS_DELETED")
		  REFERENCES "CCAT_DEV2"."LK_BOOLEAN" ("BOOLEAN_ID") DISABLE, 
		 CONSTRAINT "ADM_BUSINESS_PLANS_R05" FOREIGN KEY ("ACTIVATION_PLAN")
		  REFERENCES "CCAT_DEV2"."LK_BOOLEAN" ("BOOLEAN_ID") DISABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE INDEX "CCAT_DEV2"."ADM_BUSINESS_PAN_DEL_INDX" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("IS_DELETED") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE INDEX "CCAT_DEV2"."ADM_BUSINESS_PLAN_ACTIV_INDX" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("ACTIVATION_PLAN") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE INDEX "CCAT_DEV2"."ADM_BUSINESS_PLAN_CAMEL_INDX" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("CAMEL_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE INDEX "CCAT_DEV2"."ADM_BUSINESS_PLAN_HLR_INDX" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("HLR_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE INDEX "CCAT_DEV2"."ADM_BUSINESS_PLAN_SCID_INDX" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("SERVICE_CLASS_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_ADM_BUSINESS_PLANS" ON "CCAT_DEV2"."ADM_BUSINESS_PLANS" ("ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;
	  
  
	  CREATE TABLE "CCAT_DEV2"."LK_BOOLEAN" 
	   (	"BOOLEAN_ID" NUMBER(1,0) NOT NULL ENABLE, 
		"BOOLEAN_VALUE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		 CONSTRAINT "LK_BOOLEAN_PK" PRIMARY KEY ("BOOLEAN_ID")
	  USING INDEX (CREATE UNIQUE INDEX "CCAT_DEV2"."PK_LK_BOOLEAN" ON "CCAT_DEV2"."LK_BOOLEAN" ("BOOLEAN_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" )  ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;
	  
  
  
  

  	  CREATE TABLE "CCAT_DEV2"."ADM_HLR_PROFILES" 
	   (	
	   "HLR_ID" NUMBER(6,0) NOT NULL ENABLE, 
		"CODE" NUMBER(6,0) NOT NULL ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;

	  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_ADM_HLR_PROFILES" ON "CCAT_DEV2"."ADM_HLR_PROFILES" ("HLR_ID") 
	  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "USERS" ;
	  
	  
	  
	  
	  
	  
	  
  
  	CREATE SEQUENCE  "CCAT_DEV2"."S_ADM_BUSINESS_PLANS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 205;
    CREATE SEQUENCE  "CCAT_DEV2"."S_ADM_SERVICE_CLASSES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1902;
	
	
	
	
	ALTER TABLE ADM_HLR_PROFILES ADD (NAME varchar2(100 BYTE));
	UPDATE "CCAT_DEV2"."ADM_HLR_PROFILES" SET NAME = '1' WHERE ROWID = 'AAEGM4AAMAAKNzFAAA' AND ORA_ROWSCN = '1237770175'
	ALTER TABLE ADM_HLR_PROFILES MODIFY NAME varchar2(100 BYTE) NOT NULL ;
	
	
	
	
CREATE TABLE "CCAT_DEV2"."ADM_MARQUEE_DATA" 
   (	"ID" NUMBER(6,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_ADM_MARQUEE_DATA" ON "CCAT_DEV2"."ADM_MARQUEE_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

	  
	  
  CREATE TABLE "CCAT_DEV2"."LK_DISCONNECTION_CODES" 
   (	
   "ID" NUMBER(20,0) NOT NULL ENABLE, 
	"CODE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "LK_DISCONNECTION_CODES_R01" FOREIGN KEY ("IS_DELETED")
	  REFERENCES "CCAT_DEV2"."LK_BOOLEAN" ("BOOLEAN_ID") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "CCAT_DEV2"."ADM_DIS_CODE_DEL_INDX" ON "CCAT_DEV2"."LK_DISCONNECTION_CODES" ("IS_DELETED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "CCAT_DEV2"."PK_LK_DISCONNECTION_CODES" ON "CCAT_DEV2"."LK_DISCONNECTION_CODES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



   CREATE SEQUENCE  "CCAT_DEV2"."S_LK_DISCONNECTION_CODES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4;



  CREATE TABLE "CCAT_DEV2"."LK_PAM_PRIORITY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "LK_PAM_PRIORITY_PK" PRIMARY KEY ("ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;







CREATE TABLE "CCAT_DEV2"."LK_PAM_PERIOD" 
   (	"ID" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "LK_PAM_PERIOD_PK" PRIMARY KEY ("ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;





  CREATE TABLE "CCAT_DEV2"."LK_PAM_SCHEDULES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "LK_PAM_SCHEDULES_PK" PRIMARY KEY ("ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  



      CREATE TABLE "CCAT_DEV2"."LK_PAM_SERVICES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "LK_PAM_SERVICES_PK" PRIMARY KEY ("ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
    CREATE TABLE "CCAT_DEV2"."DSS_COLUMNS" 
   (	"DSS_PAGENAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DISPLAYNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DSS_COLUMNS_PK" PRIMARY KEY ("DSS_PAGENAME", "COLUMN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


    CREATE TABLE "CCAT_DEV2"."ETOPUP_TRANSACTIONS_TEST" 
   (	"TRANSFER_DATE" DATE, 
	"TRANSACTION_WAY" VARCHAR2(32), 
	"TRANSACTION_TYPE" VARCHAR2(32), 
	"TRANSITION_CATEGORY" VARCHAR2(32), 
	"CHANNEL_TYPE" VARCHAR2(32), 
	"SENDER_MSISDN" VARCHAR2(32), 
	"RECEIVER_MSISDN" VARCHAR2(32), 
	"SENDER_CATEGORY" VARCHAR2(32), 
	"RECEIVER_CATEGORY" VARCHAR2(32), 
	"TRANSFER_AMOUNT" NUMBER, 
	"PRODUCT" VARCHAR2(32), 
	"REQUEST_SOURCE" VARCHAR2(32)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 
 create or replace PROCEDURE "GET_OUTGO_DATA" (
   MSISDN              IN       VARCHAR2,
   FROM_DATE           IN       VARCHAR2,
   TO_DATE             IN       VARCHAR2,
   SERVICE_FLAG        IN       NUMBER,
   OUTPUT_CURSOR       OUT      sys_refcursor,
   ERROR_CODE          OUT      NUMBER,
   ERROR_DESCRIPTION   OUT      VARCHAR2
)
AS
BEGIN
   ERROR_CODE := 0;
   ERROR_DESCRIPTION := 'Sucess';

   OPEN OUTPUT_CURSOR FOR
      SELECT *  FROM etopup_transactions_test;
END;


CREATE SEQUENCE  "CCAT_DEV2"."S_ADM_TX_CODES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 20;



CREATE SEQUENCE  "CCAT_DEV2"."S_ADM_TX_TYPES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 20 ;
  



  CREATE TABLE "CCAT_DEV2"."TX_SUBSCRIBER_ADJUSTMENTS" 
   (	"ID" NUMBER(16,0) NOT NULL ENABLE,
	"MSISDN" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"MSISDN_MOD_X" NUMBER(2,0) NOT NULL ENABLE, 
	"ADJ_DATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE "USERS" ;
  
  
   CREATE SEQUENCE  "CCAT_DEV2"."S_TX_SUBSCRIBER_ADJUSTMENTS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
