import { Component, OnInit } from '@angular/core';
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons';
import { LazyLoadEvent } from 'primeng/api';
import { Table } from 'primeng/table';
import { map } from 'rxjs/operators';
import { ProfileService } from 'src/app/core/service/administrator/profile.service';
import { FeaturesService } from 'src/app/shared/services/features.service';
import { MessageService } from 'src/app/shared/services/message.service';
import { ToastService } from 'src/app/shared/services/toast.service';
@Component({
    selector: 'app-extact-profile-features',
    templateUrl: './extact-profile-features.component.html',
    styleUrls: ['./extact-profile-features.component.scss'],
})
export class ExtactProfileFeaturesComponent implements OnInit {
    tab = 'profile';
    profiles$ = this.profileService.allProfiles$.pipe(map((res) => res?.payload?.profilesList));
    faCircleCheck = faCircleCheck;
    profileId;
    profileFeatures = [
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: null,
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: null,
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: 'X',
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: 'X',
            WRITE_USER_PROFILES4: 'X',
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: 'X',
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: 'X',
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: 'X',
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: null,
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: null,
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: 'X',
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: 'X',
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: null,
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: 'X',
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: 'X',
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: 'X',
        },
        {
            profile: 'test',
            MINSAT_System_Administration: null,
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: 'X',
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: 'X',
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: 'X',
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: 'X',
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: 'X',
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: 'X',
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: 'X',
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: 'X',
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: 'X',
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: 'X',
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: 'X',
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: 'X',
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: 'X',
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: 'X',
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: 'X',
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: 'X',
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: null,
            WRITE_USER_PROFILES0: 'X',
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: 'X',
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: 'X',
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: null,
            MVNO_Administration: 'X',
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: 'X',
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: 'X',
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
        {
            profile: 'test',
            MINSAT_System_Administration: 'X',
            MVNO_Administration: null,
            Alarm_AdministrationL: 'X',
            Performance_Measurement: null,
            WRITE_SYSTEM_CONFIGs: 'X',
            WRITE_USER_PROFILES0: null,
            WRITE_USER_PROFILES1: null,
            WRITE_USER_PROFILES2: null,
            WRITE_USER_PROFILES3: null,
            WRITE_USER_PROFILES4: null,
            WRITE_USER_PROFILES5: null,
            WRITE_USER_PROFILES6: null,
            WRITE_USER_PROFILES7: null,
            WRITE_USER_PROFILES8: null,
            WRITE_USER_PROFILES9: null,
        },
    ];
    testFilters = [
        { name: 'name', value: 'name' },
        { name: 'job', value: 'job' },
        { name: 'location', value: 'location' },
        { name: 'email', value: 'email' },
    ];
    testColumns = ['name', 'job', 'email', 'location'];
    testTableColumns: any;
    testData = [
        { profile: 'Hello', name: 'X', job: null, email: 'X', location: null },
        { profile: 'Hello', name: 'X', job: null, email: 'X', location: null },
        { profile: 'Hello', name: 'X', job: null, email: 'X', location: null },
    ];
    testTabledata: any;
    dataTable: any;
    coloumns = [
        'MINSAT_System_Administration',
        'MVNO_Administration',
        'Alarm_AdministrationL',
        'Performance_Measurement',
        'WRITE_SYSTEM_CONFIGs',
        'WRITE_USER_PROFILES0',
        'WRITE_USER_PROFILES1',
        'WRITE_USER_PROFILES2',
        'WRITE_USER_PROFILES3',
        'WRITE_USER_PROFILES4',
        'WRITE_USER_PROFILES5',
        'WRITE_USER_PROFILES6',
        'WRITE_USER_PROFILES7',
        'WRITE_USER_PROFILES8',
        'WRITE_USER_PROFILES9',
    ];
    colTable;
    permissions = {
        getProfileUsers: false,
        getProfileFeatures: false,
    };
    constructor(private profileService: ProfileService, private toasterService: ToastService,
        private featuresService: FeaturesService,
        private messageService: MessageService) { }
    get keys() {
        const array = Object.keys(this.profileFeatures[0]);
        const newArr = array.map((arr) => {
            return {
                name: arr,
                value: arr,
            };
        });
        return newArr;
    }
    filter(value, dt: Table) {
        this.testTableColumns = [value.name];
        this.testTabledata = this.testData.map((el) => {
            return { profile: el.profile, [value.name]: el[value.name] };
        });
    }
    ngOnInit(): void {
        this.setPermissions()
        // begin test
        this.testTableColumns = this.testColumns;
        this.testTabledata = this.testData;
        //end test
    }
    clearFilter() {
        this.testTableColumns = this.testColumns;
        this.testTabledata = this.testData;
    }
    switchTab(tab) {
        this.tab = tab;
    }
   
    setPermissions() {
        let findSubscriberPermissions: Map<number, string> = new Map()
            .set(269, 'getProfileUsers')
            .set(270, 'getProfileFeatures')
        this.featuresService.checkUserPermissions(findSubscriberPermissions);
        this.permissions.getProfileUsers = this.featuresService.getPermissionValue(269);
        this.permissions.getProfileFeatures = this.featuresService.getPermissionValue(270);

    }
}
